name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Publish when a new version tag is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi-publish
    permissions:
      id-token: write  # OIDC authentication with PyPI
      contents: read   # To check out the repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: |
          uv pip install --system --break-system-packages build
      
      - name: Build package
        run: |
          uv build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true 